TaskManagement1/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using TaskManagement1.Data;
using TaskManagement1.Models;
using TaskManagement1.Services;

namespace TaskManagement1.Controllers
{
    [Route("api/[controller]")]
	[ApiController]
	public class MessagesController : Controller
    {
        private readonly IEmailService _emailService;
        private readonly TaskManagementDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public MessagesController(IEmailService emailService, TaskManagementDbContext context, UserManager<AppUser> userManager) 
        {
            _emailService = emailService; 
            _context = context;
            _userManager = userManager;
        }


        //[HttpGet]
        //public IActionResult SendMail() 
        //{
        //    return ViewColumn();
        //}



        //Müşteri mesajlarını görsün



        [Authorize(Roles ="Admin,Müşteri")]

        [HttpGet("create")]
        public async Task<IActionResult> SendMail() 
        {
            var user = await _userManager.GetUserAsync(User);
            var usermail = user?.Email;
            ViewBag.usermail = usermail;

            var personel = _context.Users.Where(a=>a.Role == "Personel").Select(a=>a.Email).ToList();
            ViewBag.personel = new SelectList(personel, "Role");
            return View();
        }
        //Mail gönderdikten sonra homepage'e dönüş.
                                                           
        [HttpPost("send")]
        public async Task<IActionResult> SendMail([FromForm]Messages request)
        {
            _context.Messagess.Add(request);
            await _context.SaveChangesAsync();
            
            _emailService.SendEmail(request);
            return RedirectToAction("Index","Home");
        }

        [HttpGet]
        public async Task<IActionResult> MyMessages()
        {
            return View();
        }
    }
}

TaskManagement1/Controllers/MusteriController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TaskManagement1.Data;
using TaskManagement1.Models;
using TaskManagement1.Services;

namespace TaskManagement1.Controllers
{
	[Route("api/[controller]")]
	[ApiController]
	public class MusteriController : Controller
	{
		private readonly TaskManagementDbContext _context;
		private readonly IEmailService _emailservice;
		private readonly UserManager<AppUser> _usermanager;
		public MusteriController(TaskManagementDbContext context, IEmailService emailservice, UserManager<AppUser> userManager)
		{
			_context = context;
			_emailservice = emailservice;
			_usermanager = userManager;
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			//var messages = _context.Messagess.ToList();

			var musteri = await _usermanager.GetUserAsync(User);
			var musterimail = musteri?.Email;
			ViewBag.Email = musterimail;

			var ilgilimesajlar = _context.Messagess.Where(a => a.ReceiverId == musterimail || a.SenderId==musterimail).ToList();

			return View(ilgilimesajlar);
		}

        [HttpGet("Musteri/details/id")]
        public async Task<IActionResult> Details(int? id)
        {
			var mesajlar = await _context.Messagess.FirstOrDefaultAsync(m => m.Id == id);
            mesajlar.Status = 1;
            _context.Messagess.Update(mesajlar);
            await _context.SaveChangesAsync();
            return View(mesajlar);
        }

		[HttpGet("Create/id")]
		public async Task<IActionResult> Yanıtla(int? id)
		{
			var musteri = await _usermanager.GetUserAsync(User);
			var musterimail = musteri?.Email;
			ViewBag.Email = musterimail;


			var mesaj = await _context.Messagess.FirstOrDefaultAsync(m => m.Id == id);




			return View(mesaj);
		}

		[HttpPost("send")]

		public async Task<IActionResult> Yanıtla([FromForm] Messages request)
		{
			_context.Messagess.Add(request);
			await _context.SaveChangesAsync();

			_emailservice.SendEmail(request);
			return Ok();
		}

	}
}

TaskManagement1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Görev Yönetim</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   @* <link rel="stylesheet" href="/css/mycss.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/TaskManagement1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light navbar border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Görev Yönetim</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         @if(User.IsInRole("Personel") || User.IsInRole("Müşteri"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-fill"></i> Home</a>
                        </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"><i class="bi bi-file-earmark-lock2-fill"></i> Privacy</a>
                        </li>
                        @if (User.IsInRole("Müşteri")) {
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Messages" asp-action="SendMail"><i class="bi bi-envelope-arrow-up-fill"></i> SendMail</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Musteri" asp-action="Index"><i class="bi bi-envelope-fill"></i> Mesajlar</a>
                            </li>
                        }
                        @if (User.IsInRole("Personel"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Personel" asp-action="Index"><i class="bi bi-envelope-arrow-up-fill"></i>> Mail</a>
                            </li>
                        }
                        
                    </ul>
                </div>
                <partial name="_LoginPartial"    />
            </div>
        </nav>
        <style>
            .navbar{
                background-color: aliceblue;
                border-bottom: 2px solid #2980;
                border-radius:8px;
                padding:10px;

            }
        </style>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @* <div class="container">
            &copy; 2024 - TaskManagement1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div> *@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>